
// export const TOTAL_EXERCISES = 3 // TOTAL EXERCISES TO BE PRACTICED IN A LEVEL
export const TOTAL_EXERCISES = 2 // TOTAL EXERCISES TO BE PRACTICED IN A LEVEL
export const MIN_PASSING_SCORE = 2
export const XP_EARN_PER_CORRECT = 2
export const XP_TOTAL_COMPLETE = 10
export const FREE_LEVELS = 3
